#!/usr/bin/env bash
set -e -u -o pipefail

source ../../../build-common.sh

check_linux_enabled "$@"

function list_mods {
    find "$HERE/lib" -name "*.ml" -print | mod_names
}

MODULES=$(list_mods | sort -u | my_join)

cat >$HERE/_oasis <<EOF
#AUTOGENERATED FILE; EDIT oasis.sh INSTEAD

OASISFormat:  0.2
OCamlVersion: >= 3.12
Name:         async_scheduler
Version:      107.01
Synopsis:     Jane Street Capital's asynchronous execution library (scheduler)
Authors:      Jane street capital
Copyrights:   (C) 2008-2011 Jane Street Capital LLC
License:      LGPL-2.1 with OCaml linking exception
LicenseFile:  LICENSE
Plugins:      StdFiles (0.2),
              DevFiles (0.2),
              META (0.2)
BuildTools:   ocamlbuild
Description:  Jane Street Capital's asynchronous execution library
FindlibVersion: >= 1.2.7
XStdFilesAUTHORS: false
XStdFilesINSTALLFilename: INSTALL
XStdFilesREADME: false

Flag linux
  Description: Enable linux specific extensions
  Default$:    $enable_linux

PreBuildCommand: mkdir -p _build; cp lib/*mlh _build/
PreDistCleanCommand: \$rm lib/version_defaults.mlh lib/config.mlh

Library async_scheduler
  Path:               lib
  FindlibName:        async_scheduler
  Pack:               true
  Modules:            ${MODULES}
  BuildDepends:       sexplib.syntax,
                      sexplib,
                      fieldslib.syntax,
                      fieldslib,
                      bin_prot,
                      bin_prot.syntax,
                      pa_ounit,
                      pa_pipebang,
                      core,
                      async_core,
                      threads

EOF

make_tags "$HERE/_tags" <<EOF
# remove this part when oasis supports Pack: true
$(tag_for_pack Async_scheduler $HERE/lib/*.ml)

<lib/*.ml{,i}>: syntax_camlp4o
"lib/async_unix.ml": pkg_camlp4.macro
"lib/raw_scheduler.ml": pkg_camlp4.macro
<lib/writer.ml{,i}>: pkg_camlp4.macro
EOF

cat >$HERE/lib/config.mlh <<EOF
$(if [[ "$enable_linux" == "true" ]]; then echo "DEFINE LINUX_EXT"; fi)
EOF

cd $HERE
oasis setup
enable_pack_in_setup_ml async_scheduler

./configure "$enable_linux_default" "$@"

