#!/usr/bin/env bash
set -e -u -o pipefail

source ../../build-common.sh

cat >$HERE/_oasis <<EOF
#AUTOGENERATED FILE; EDIT oasis.sh INSTEAD

OASISFormat:  0.3
OCamlVersion: >= 3.12
Name:         async
Version:      $core_version
Synopsis:     Jane Street Capital's asynchronous execution library
Authors:      Jane street capital
Copyrights:   (C) 2008-2012 Jane Street Capital LLC
License:      LGPL-2.1 with OCaml linking exception
LicenseFile:  LICENSE
Plugins:      StdFiles (0.3), DevFiles (0.3), META (0.3)
BuildTools:   ocamlbuild
Description:  Jane Street Capital's asynchronous execution library
FindlibVersion: >= 1.2.7
XStdFilesAUTHORS: false
XStdFilesINSTALLFilename: INSTALL
XStdFilesREADME: false

Library async
  Path:               lib
  FindlibName:        async
  Pack:               true
  Modules:            $(list_mods "$HERE/lib")
  BuildDepends:       async_core,
                      async_unix,
                      async_extra,
                      threads


Document "async"
  Title:                Jane street's async library
  Type:                 ocamlbuild (0.3)
  BuildTools+:          ocamldoc
  XOCamlbuildPath:      lib
  XOCamlbuildLibraries: async

EOF

make_tags $HERE/_tags <<EOF
# <lib_test/*.ml{,i}>: syntax_camlp4o
EOF

make_myocamlbuild_default "$HERE/myocamlbuild.ml"

cd $HERE
rm -f setup.ml
oasis setup
