#!/usr/bin/env bash
set -e -u -o pipefail

source ../../build-common.sh

cat >$HERE/_oasis <<EOF
#AUTOGENERATED FILE; EDIT oasis.sh INSTEAD
OASISFormat:  0.3
OCamlVersion: >= 3.12
Name:         typehashlib
Version:      0.1.1
Synopsis:     Syntax extension for deriving "typehash" functions automatically.
Authors:      Jane street capital
Copyrights:   (C) 2009-2011 Jane Street Capital LLC
License:      LGPL-2.1 with OCaml linking exception
LicenseFile:  LICENSE
Plugins:      StdFiles (0.3), DevFiles (0.3), META (0.3)
XStdFilesREADME: false
XStdFilesAUTHORS: false
XStdFilesINSTALLFilename: INSTALL
BuildTools:   ocamlbuild

Library typehashlib
  Path:               lib
  Modules:            Typehash
  FindlibName:        typehashlib

Library pa_typehash
  Path:               syntax
  Modules:            Pa_typehash
  FindlibParent:      typehashlib
  FindlibName:        syntax
  BuildDepends:       camlp4.lib,
                      camlp4.quotations,
                      type_conv (>= 3.0.5)
  CompiledObject:     byte
  XMETAType:          syntax
  XMETARequires:      camlp4,type_conv,typehashlib
  XMETADescription:   Syntax extension for "with typehash"
EOF

make_tags $HERE/_tags <<EOF
<syntax/pa_typehash.ml>: syntax_camlp4o,pkg_camlp4.extend
EOF

cd $HERE
oasis setup
./configure "$@"

