#!/bin/bash
set -e -u -o pipefail

here="$(dirname "${BASH_SOURCE[0]}")"

cat >$here/_oasis <<EOF
#AUTOGENERATED FILE; EDIT oasis.sh INSTEAD
OASISFormat:  0.2
OCamlVersion: >= 3.12
Name:         comparelib
Version:      0.1.1
Synopsis:     Syntax extension for deriving "compare" functions automatically.
Authors:      Jane street capital
Copyrights:   (C) 2009-2011 Jane Street Capital LLC
License:      LGPL-2.1 with OCaml linking exception
LicenseFile:  LICENSE
Plugins:      StdFiles (0.2),
              DevFiles (0.2),
              META (0.2)
XStdFilesREADME: false
XStdFilesAUTHORS: false
XStdFilesINSTALLFilename: INSTALL
BuildTools:   ocamlbuild

Library comparelib
  Path:               lib
  Modules:
  FindlibName:        comparelib
  XMETAType:          library

Library pa_compare
  Path:               syntax
  Modules:            Pa_compare
  FindlibParent:      comparelib
  FindlibName:        syntax
  BuildDepends:       camlp4.lib,
                      camlp4.quotations,
                      type-conv (>= 2.0.1)
  CompiledObject:     byte
  XMETAType:          syntax
  XMETARequires:      camlp4,type-conv,comparelib
  XMETADescription:   Syntax extension for "with compare"
EOF

cat >$here/_tags <<EOF
# OASIS_START
# OASIS_STOP
<syntax/pa_compare.ml>: syntax_camlp4o
EOF

mkdir -p $here/lib

cd $here
oasis setup
./configure "$@"

