#!/usr/bin/env bash
set -e -u -o pipefail

source ../../build-common.sh

cat >$HERE/_oasis <<EOF
#AUTOGENERATED FILE; EDIT oasis.sh INSTEAD
OASISFormat:  0.3
OCamlVersion: >= 3.12
Name:         type_conv
Version:      $core_version
Synopsis:     support library for preprocessor type conversions
Authors:      Martin Sandin,
              Markus Mottl,
              Jane Street Capital, LLC
License:      LGPL-2.1 with OCaml linking exception
LicenseFile:  LICENSE
Plugins:      StdFiles (0.3), DevFiles (0.3), META (0.3)
BuildTools:   ocamlbuild, camlp4o
XStdFilesAUTHORS: false
XStdFilesINSTALLFilename: INSTALL
XStdFilesREADME: false

Library pa_type_conv
  Path:               lib
  FindlibName:        type_conv
  Modules:            Pa_type_conv
  BuildDepends:       camlp4.quotations, camlp4.extend
  CompiledObject:     byte
  XMETAType:          syntax
  XMETARequires:      camlp4
  XMETADescription:   Syntax extension for type_conv

Document "type_conv"
  Title:                API reference for Type_conv
  Type:                 ocamlbuild (0.3)
  BuildTools+:          ocamldoc
  XOCamlbuildPath:      lib
  XOCamlbuildLibraries: type_conv
EOF

make_tags $HERE/_tags <<EOF
<lib/pa_type_conv.ml>: syntax_camlp4o
EOF

make_myocamlbuild $HERE/myocamlbuild.ml <<EOF
Ocamlbuild_plugin.dispatch
  begin
    function
      | After_rules as e ->
          flag ["compile"; "ocaml"] (S [A "-w"; A "@Ae" ]);
          dispatch_default e
      | e -> dispatch_default e
  end
;;
EOF

cd $HERE
oasis setup
